apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-mine
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: helm-nginx
      version: '>0.0.x'
      sourceRef:
        kind: GitRepository
        name: nginx-mine
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
